spring.application.name=emprestimos
spring.datasource.url=jdbc:postgresql://Postgres.railway.internal:5432/${{ Postgres.PGDATABASE }}
spring.datasource.username=${{ Postgres.PGUSER }}
spring.datasource.password=${{ Postgres.PGPASSWORD }}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect