spring.application.name=emprestimos

spring.datasource.url=jdbc:postgresql://emprestimos.railway.internal

spring.datasource.username=Cel37
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect